#!/bin/bash

RCM_EXTENSION_VERSION=0.12.0

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-php-setup-drupal [options]

Options:
   --php-version
        Set the version of PHP.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   rcm-php-apt
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-php-setup-drupal
____

# Dependency.

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code 'php_version="'$php_version'"'
____

INDENT+="    " \
rcm-php-apt $isfast \
    --php-version="$php_version" \
    --extension=common \
    --extension=gd \
    --extension=mysql \
    --extension=imap \
    --extension=cli \
    --extension=fpm \
    --extension=curl \
    --extension=intl \
    --extension=pspell \
    --extension=sqlite3 \
    --extension=tidy \
    --extension=xmlrpc \
    --extension=xsl \
    --extension=zip \
    --extension=mbstring \
    --extension=soap \
    --extension=opcache \
    ; [ ! $? -eq 0 ] && x

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --php-version
# )
# FLAG_VALUE=(
# )
# EOF
# clear
